#cloud-config
package_update: true
packages:
  - apache2
  - mysql-server
  - php
  - libapache2-mod-php
  - php-mysql
  - redis-server
  - php-redis

runcmd:
  - [ systemctl, enable, --now, apache2 ]
  - [ systemctl, enable, --now, mysql ]
  - [ systemctl, enable, --now, redis-server ]
